[ctrl]
     # 设置程序输出的程度，缺省为1
     print_level =               1
     # 设置Rayon和OpenMP的并行数，缺省为1
     num_threads =               4
     # 设置使用的电子结构方法，缺省为HF
     xc =                        "x3lyp" 
     # 设置（辅助）基组的路径。如果找不到该路径，则创建该路径，并从BSE下载
     # 注意：计算节点需支持连接外网。
     basis_path =                "../../../basis-set-pool/cc-pVDZ"
     auxbas_path =               "../../../basis-set-pool/def2-SV(P)-JKFIT" 
     # 辅助基函数自动生成设置
     even_tempered_basis =       true
     etb_start_atom_number =     1
     etb_beta =                  1.0
     # 使用resolution-of-identity (RI)技术处理四中心积分（缺省）
     eri_type =                  "ri_v"
     use_ri_symm =               true
     charge =                    0.0
     spin =                      1.0
     spin_polarization =         false
     mixer =                     "diis"
     num_max_diis =              8
     start_diis_cycle =          1
     mix_param =                 1.1
     max_scf_cycle =             100
     scf_acc_rho =               1.0e-5
     scf_acc_eev =               1.0e-5
     scf_acc_etot =              1.0e-8
     initial_guess =             "sad"
     chkfile =                   "none"
     fchk =                      false
     pruning =                   "nwchem"
     radial_grid_method =        "treutler"
     external_grids =            "none"

[geom]
     name = "NH3"
     unit = "angstrom"
     position = '''
        N  -2.1988391019      1.8973746268      0.0000000000
        H  -1.1788391019      1.8973746268      0.0000000000
        H  -2.5388353987      1.0925460144     -0.5263586446
        H  -2.5388400276      2.7556271745     -0.4338224694'''

